import { Mulish } from "next/font/google";
import "../../globals.css";
import { CheckLogin } from "@/Helpers/CheckLogin";

const mulish = Mulish({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: {
    default: "Login",
  },
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <CheckLogin> {children}</CheckLogin>
      </body>
    </html>
  );
}
